// source: task.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = globalThis;

var google_protobuf_duration_pb = require('google-protobuf/google/protobuf/duration_pb.js');
goog.object.extend(proto, google_protobuf_duration_pb);
goog.exportSymbol('proto.neurun.CreateTaskRequest', null, global);
goog.exportSymbol('proto.neurun.CreateTaskRequest.PayloadCase', null, global);
goog.exportSymbol('proto.neurun.HTTPApiKeyAuth', null, global);
goog.exportSymbol('proto.neurun.HTTPApiKeyLocation', null, global);
goog.exportSymbol('proto.neurun.HTTPAuth', null, global);
goog.exportSymbol('proto.neurun.HTTPAuth.AuthTypeCase', null, global);
goog.exportSymbol('proto.neurun.HTTPBasicAuth', null, global);
goog.exportSymbol('proto.neurun.HTTPBearerAuth', null, global);
goog.exportSymbol('proto.neurun.HTTPPayload', null, global);
goog.exportSymbol('proto.neurun.LogPayload', null, global);
goog.exportSymbol('proto.neurun.Task', null, global);
goog.exportSymbol('proto.neurun.Task.PayloadCase', null, global);
goog.exportSymbol('proto.neurun.TaskStatus', null, global);
goog.exportSymbol('proto.neurun.TaskType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.neurun.CreateTaskRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.neurun.CreateTaskRequest.repeatedFields_, proto.neurun.CreateTaskRequest.oneofGroups_);
};
goog.inherits(proto.neurun.CreateTaskRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.neurun.CreateTaskRequest.displayName = 'proto.neurun.CreateTaskRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.neurun.Task = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.neurun.Task.repeatedFields_, proto.neurun.Task.oneofGroups_);
};
goog.inherits(proto.neurun.Task, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.neurun.Task.displayName = 'proto.neurun.Task';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.neurun.LogPayload = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.neurun.LogPayload, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.neurun.LogPayload.displayName = 'proto.neurun.LogPayload';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.neurun.HTTPPayload = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.neurun.HTTPPayload, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.neurun.HTTPPayload.displayName = 'proto.neurun.HTTPPayload';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.neurun.HTTPAuth = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.neurun.HTTPAuth.oneofGroups_);
};
goog.inherits(proto.neurun.HTTPAuth, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.neurun.HTTPAuth.displayName = 'proto.neurun.HTTPAuth';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.neurun.HTTPBasicAuth = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.neurun.HTTPBasicAuth, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.neurun.HTTPBasicAuth.displayName = 'proto.neurun.HTTPBasicAuth';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.neurun.HTTPBearerAuth = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.neurun.HTTPBearerAuth, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.neurun.HTTPBearerAuth.displayName = 'proto.neurun.HTTPBearerAuth';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.neurun.HTTPApiKeyAuth = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.neurun.HTTPApiKeyAuth, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.neurun.HTTPApiKeyAuth.displayName = 'proto.neurun.HTTPApiKeyAuth';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.neurun.CreateTaskRequest.repeatedFields_ = [8];

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.neurun.CreateTaskRequest.oneofGroups_ = [[6,7]];

/**
 * @enum {number}
 */
proto.neurun.CreateTaskRequest.PayloadCase = {
  PAYLOAD_NOT_SET: 0,
  LOGPAYLOAD: 6,
  HTTPPAYLOAD: 7
};

/**
 * @return {proto.neurun.CreateTaskRequest.PayloadCase}
 */
proto.neurun.CreateTaskRequest.prototype.getPayloadCase = function() {
  return /** @type {proto.neurun.CreateTaskRequest.PayloadCase} */(jspb.Message.computeOneofCase(this, proto.neurun.CreateTaskRequest.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.neurun.CreateTaskRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.neurun.CreateTaskRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.neurun.CreateTaskRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neurun.CreateTaskRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
name: jspb.Message.getFieldWithDefault(msg, 1, ""),
type: jspb.Message.getFieldWithDefault(msg, 2, 0),
retries: jspb.Message.getFieldWithDefault(msg, 3, 0),
retrydelay: (f = msg.getRetrydelay()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
condition: (f = jspb.Message.getField(msg, 5)) == null ? undefined : f,
logpayload: (f = msg.getLogpayload()) && proto.neurun.LogPayload.toObject(includeInstance, f),
httppayload: (f = msg.getHttppayload()) && proto.neurun.HTTPPayload.toObject(includeInstance, f),
nextList: jspb.Message.toObjectList(msg.getNextList(),
    proto.neurun.CreateTaskRequest.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.neurun.CreateTaskRequest}
 */
proto.neurun.CreateTaskRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.neurun.CreateTaskRequest;
  return proto.neurun.CreateTaskRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.neurun.CreateTaskRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.neurun.CreateTaskRequest}
 */
proto.neurun.CreateTaskRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {!proto.neurun.TaskType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setRetries(value);
      break;
    case 4:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setRetrydelay(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setCondition(value);
      break;
    case 6:
      var value = new proto.neurun.LogPayload;
      reader.readMessage(value,proto.neurun.LogPayload.deserializeBinaryFromReader);
      msg.setLogpayload(value);
      break;
    case 7:
      var value = new proto.neurun.HTTPPayload;
      reader.readMessage(value,proto.neurun.HTTPPayload.deserializeBinaryFromReader);
      msg.setHttppayload(value);
      break;
    case 8:
      var value = new proto.neurun.CreateTaskRequest;
      reader.readMessage(value,proto.neurun.CreateTaskRequest.deserializeBinaryFromReader);
      msg.addNext(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.neurun.CreateTaskRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.neurun.CreateTaskRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.neurun.CreateTaskRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neurun.CreateTaskRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getRetries();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getRetrydelay();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getLogpayload();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.neurun.LogPayload.serializeBinaryToWriter
    );
  }
  f = message.getHttppayload();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.neurun.HTTPPayload.serializeBinaryToWriter
    );
  }
  f = message.getNextList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      proto.neurun.CreateTaskRequest.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.neurun.CreateTaskRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.neurun.CreateTaskRequest} returns this
 */
proto.neurun.CreateTaskRequest.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional TaskType type = 2;
 * @return {!proto.neurun.TaskType}
 */
proto.neurun.CreateTaskRequest.prototype.getType = function() {
  return /** @type {!proto.neurun.TaskType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.neurun.TaskType} value
 * @return {!proto.neurun.CreateTaskRequest} returns this
 */
proto.neurun.CreateTaskRequest.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional uint32 retries = 3;
 * @return {number}
 */
proto.neurun.CreateTaskRequest.prototype.getRetries = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.neurun.CreateTaskRequest} returns this
 */
proto.neurun.CreateTaskRequest.prototype.setRetries = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional google.protobuf.Duration retryDelay = 4;
 * @return {?proto.google.protobuf.Duration}
 */
proto.neurun.CreateTaskRequest.prototype.getRetrydelay = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 4));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.neurun.CreateTaskRequest} returns this
*/
proto.neurun.CreateTaskRequest.prototype.setRetrydelay = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.neurun.CreateTaskRequest} returns this
 */
proto.neurun.CreateTaskRequest.prototype.clearRetrydelay = function() {
  return this.setRetrydelay(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.neurun.CreateTaskRequest.prototype.hasRetrydelay = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string condition = 5;
 * @return {string}
 */
proto.neurun.CreateTaskRequest.prototype.getCondition = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.neurun.CreateTaskRequest} returns this
 */
proto.neurun.CreateTaskRequest.prototype.setCondition = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.neurun.CreateTaskRequest} returns this
 */
proto.neurun.CreateTaskRequest.prototype.clearCondition = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.neurun.CreateTaskRequest.prototype.hasCondition = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional LogPayload logPayload = 6;
 * @return {?proto.neurun.LogPayload}
 */
proto.neurun.CreateTaskRequest.prototype.getLogpayload = function() {
  return /** @type{?proto.neurun.LogPayload} */ (
    jspb.Message.getWrapperField(this, proto.neurun.LogPayload, 6));
};


/**
 * @param {?proto.neurun.LogPayload|undefined} value
 * @return {!proto.neurun.CreateTaskRequest} returns this
*/
proto.neurun.CreateTaskRequest.prototype.setLogpayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 6, proto.neurun.CreateTaskRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.neurun.CreateTaskRequest} returns this
 */
proto.neurun.CreateTaskRequest.prototype.clearLogpayload = function() {
  return this.setLogpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.neurun.CreateTaskRequest.prototype.hasLogpayload = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional HTTPPayload httpPayload = 7;
 * @return {?proto.neurun.HTTPPayload}
 */
proto.neurun.CreateTaskRequest.prototype.getHttppayload = function() {
  return /** @type{?proto.neurun.HTTPPayload} */ (
    jspb.Message.getWrapperField(this, proto.neurun.HTTPPayload, 7));
};


/**
 * @param {?proto.neurun.HTTPPayload|undefined} value
 * @return {!proto.neurun.CreateTaskRequest} returns this
*/
proto.neurun.CreateTaskRequest.prototype.setHttppayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 7, proto.neurun.CreateTaskRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.neurun.CreateTaskRequest} returns this
 */
proto.neurun.CreateTaskRequest.prototype.clearHttppayload = function() {
  return this.setHttppayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.neurun.CreateTaskRequest.prototype.hasHttppayload = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * repeated CreateTaskRequest next = 8;
 * @return {!Array<!proto.neurun.CreateTaskRequest>}
 */
proto.neurun.CreateTaskRequest.prototype.getNextList = function() {
  return /** @type{!Array<!proto.neurun.CreateTaskRequest>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.neurun.CreateTaskRequest, 8));
};


/**
 * @param {!Array<!proto.neurun.CreateTaskRequest>} value
 * @return {!proto.neurun.CreateTaskRequest} returns this
*/
proto.neurun.CreateTaskRequest.prototype.setNextList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.neurun.CreateTaskRequest=} opt_value
 * @param {number=} opt_index
 * @return {!proto.neurun.CreateTaskRequest}
 */
proto.neurun.CreateTaskRequest.prototype.addNext = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.neurun.CreateTaskRequest, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.neurun.CreateTaskRequest} returns this
 */
proto.neurun.CreateTaskRequest.prototype.clearNextList = function() {
  return this.setNextList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.neurun.Task.repeatedFields_ = [10];

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.neurun.Task.oneofGroups_ = [[8,9]];

/**
 * @enum {number}
 */
proto.neurun.Task.PayloadCase = {
  PAYLOAD_NOT_SET: 0,
  LOGPAYLOAD: 8,
  HTTPPAYLOAD: 9
};

/**
 * @return {proto.neurun.Task.PayloadCase}
 */
proto.neurun.Task.prototype.getPayloadCase = function() {
  return /** @type {proto.neurun.Task.PayloadCase} */(jspb.Message.computeOneofCase(this, proto.neurun.Task.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.neurun.Task.prototype.toObject = function(opt_includeInstance) {
  return proto.neurun.Task.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.neurun.Task} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neurun.Task.toObject = function(includeInstance, msg) {
  var f, obj = {
id: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
name: jspb.Message.getFieldWithDefault(msg, 2, ""),
type: jspb.Message.getFieldWithDefault(msg, 3, 0),
status: jspb.Message.getFieldWithDefault(msg, 4, 0),
retries: jspb.Message.getFieldWithDefault(msg, 5, 0),
retrydelay: (f = msg.getRetrydelay()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
condition: (f = jspb.Message.getField(msg, 7)) == null ? undefined : f,
logpayload: (f = msg.getLogpayload()) && proto.neurun.LogPayload.toObject(includeInstance, f),
httppayload: (f = msg.getHttppayload()) && proto.neurun.HTTPPayload.toObject(includeInstance, f),
nextList: jspb.Message.toObjectList(msg.getNextList(),
    proto.neurun.Task.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.neurun.Task}
 */
proto.neurun.Task.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.neurun.Task;
  return proto.neurun.Task.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.neurun.Task} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.neurun.Task}
 */
proto.neurun.Task.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {!proto.neurun.TaskType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 4:
      var value = /** @type {!proto.neurun.TaskStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setRetries(value);
      break;
    case 6:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setRetrydelay(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setCondition(value);
      break;
    case 8:
      var value = new proto.neurun.LogPayload;
      reader.readMessage(value,proto.neurun.LogPayload.deserializeBinaryFromReader);
      msg.setLogpayload(value);
      break;
    case 9:
      var value = new proto.neurun.HTTPPayload;
      reader.readMessage(value,proto.neurun.HTTPPayload.deserializeBinaryFromReader);
      msg.setHttppayload(value);
      break;
    case 10:
      var value = new proto.neurun.Task;
      reader.readMessage(value,proto.neurun.Task.deserializeBinaryFromReader);
      msg.addNext(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.neurun.Task.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.neurun.Task.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.neurun.Task} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neurun.Task.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getRetries();
  if (f !== 0) {
    writer.writeUint32(
      5,
      f
    );
  }
  f = message.getRetrydelay();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getLogpayload();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.neurun.LogPayload.serializeBinaryToWriter
    );
  }
  f = message.getHttppayload();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.neurun.HTTPPayload.serializeBinaryToWriter
    );
  }
  f = message.getNextList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      10,
      f,
      proto.neurun.Task.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.neurun.Task.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.neurun.Task} returns this
 */
proto.neurun.Task.prototype.setId = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.neurun.Task} returns this
 */
proto.neurun.Task.prototype.clearId = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.neurun.Task.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.neurun.Task.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.neurun.Task} returns this
 */
proto.neurun.Task.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional TaskType type = 3;
 * @return {!proto.neurun.TaskType}
 */
proto.neurun.Task.prototype.getType = function() {
  return /** @type {!proto.neurun.TaskType} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.neurun.TaskType} value
 * @return {!proto.neurun.Task} returns this
 */
proto.neurun.Task.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional TaskStatus status = 4;
 * @return {!proto.neurun.TaskStatus}
 */
proto.neurun.Task.prototype.getStatus = function() {
  return /** @type {!proto.neurun.TaskStatus} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.neurun.TaskStatus} value
 * @return {!proto.neurun.Task} returns this
 */
proto.neurun.Task.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional uint32 retries = 5;
 * @return {number}
 */
proto.neurun.Task.prototype.getRetries = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.neurun.Task} returns this
 */
proto.neurun.Task.prototype.setRetries = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional google.protobuf.Duration retryDelay = 6;
 * @return {?proto.google.protobuf.Duration}
 */
proto.neurun.Task.prototype.getRetrydelay = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 6));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.neurun.Task} returns this
*/
proto.neurun.Task.prototype.setRetrydelay = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.neurun.Task} returns this
 */
proto.neurun.Task.prototype.clearRetrydelay = function() {
  return this.setRetrydelay(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.neurun.Task.prototype.hasRetrydelay = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string condition = 7;
 * @return {string}
 */
proto.neurun.Task.prototype.getCondition = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.neurun.Task} returns this
 */
proto.neurun.Task.prototype.setCondition = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.neurun.Task} returns this
 */
proto.neurun.Task.prototype.clearCondition = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.neurun.Task.prototype.hasCondition = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional LogPayload logPayload = 8;
 * @return {?proto.neurun.LogPayload}
 */
proto.neurun.Task.prototype.getLogpayload = function() {
  return /** @type{?proto.neurun.LogPayload} */ (
    jspb.Message.getWrapperField(this, proto.neurun.LogPayload, 8));
};


/**
 * @param {?proto.neurun.LogPayload|undefined} value
 * @return {!proto.neurun.Task} returns this
*/
proto.neurun.Task.prototype.setLogpayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 8, proto.neurun.Task.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.neurun.Task} returns this
 */
proto.neurun.Task.prototype.clearLogpayload = function() {
  return this.setLogpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.neurun.Task.prototype.hasLogpayload = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional HTTPPayload httpPayload = 9;
 * @return {?proto.neurun.HTTPPayload}
 */
proto.neurun.Task.prototype.getHttppayload = function() {
  return /** @type{?proto.neurun.HTTPPayload} */ (
    jspb.Message.getWrapperField(this, proto.neurun.HTTPPayload, 9));
};


/**
 * @param {?proto.neurun.HTTPPayload|undefined} value
 * @return {!proto.neurun.Task} returns this
*/
proto.neurun.Task.prototype.setHttppayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 9, proto.neurun.Task.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.neurun.Task} returns this
 */
proto.neurun.Task.prototype.clearHttppayload = function() {
  return this.setHttppayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.neurun.Task.prototype.hasHttppayload = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * repeated Task next = 10;
 * @return {!Array<!proto.neurun.Task>}
 */
proto.neurun.Task.prototype.getNextList = function() {
  return /** @type{!Array<!proto.neurun.Task>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.neurun.Task, 10));
};


/**
 * @param {!Array<!proto.neurun.Task>} value
 * @return {!proto.neurun.Task} returns this
*/
proto.neurun.Task.prototype.setNextList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 10, value);
};


/**
 * @param {!proto.neurun.Task=} opt_value
 * @param {number=} opt_index
 * @return {!proto.neurun.Task}
 */
proto.neurun.Task.prototype.addNext = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 10, opt_value, proto.neurun.Task, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.neurun.Task} returns this
 */
proto.neurun.Task.prototype.clearNextList = function() {
  return this.setNextList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.neurun.LogPayload.prototype.toObject = function(opt_includeInstance) {
  return proto.neurun.LogPayload.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.neurun.LogPayload} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neurun.LogPayload.toObject = function(includeInstance, msg) {
  var f, obj = {
message: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.neurun.LogPayload}
 */
proto.neurun.LogPayload.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.neurun.LogPayload;
  return proto.neurun.LogPayload.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.neurun.LogPayload} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.neurun.LogPayload}
 */
proto.neurun.LogPayload.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.neurun.LogPayload.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.neurun.LogPayload.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.neurun.LogPayload} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neurun.LogPayload.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string message = 1;
 * @return {string}
 */
proto.neurun.LogPayload.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.neurun.LogPayload} returns this
 */
proto.neurun.LogPayload.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.neurun.HTTPPayload.prototype.toObject = function(opt_includeInstance) {
  return proto.neurun.HTTPPayload.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.neurun.HTTPPayload} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neurun.HTTPPayload.toObject = function(includeInstance, msg) {
  var f, obj = {
url: jspb.Message.getFieldWithDefault(msg, 1, ""),
method: jspb.Message.getFieldWithDefault(msg, 2, ""),
body: msg.getBody_asB64(),
headersMap: (f = msg.getHeadersMap()) ? f.toObject(includeInstance, undefined) : [],
queryparamsMap: (f = msg.getQueryparamsMap()) ? f.toObject(includeInstance, undefined) : [],
timeout: (f = msg.getTimeout()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
auth: (f = msg.getAuth()) && proto.neurun.HTTPAuth.toObject(includeInstance, f),
followredirects: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
verifyssl: jspb.Message.getBooleanFieldWithDefault(msg, 9, false),
expectedstatuscode: jspb.Message.getFieldWithDefault(msg, 10, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.neurun.HTTPPayload}
 */
proto.neurun.HTTPPayload.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.neurun.HTTPPayload;
  return proto.neurun.HTTPPayload.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.neurun.HTTPPayload} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.neurun.HTTPPayload}
 */
proto.neurun.HTTPPayload.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setUrl(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setMethod(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBody(value);
      break;
    case 4:
      var value = msg.getHeadersMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readStringRequireUtf8, jspb.BinaryReader.prototype.readStringRequireUtf8, null, "", "");
         });
      break;
    case 5:
      var value = msg.getQueryparamsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readStringRequireUtf8, jspb.BinaryReader.prototype.readStringRequireUtf8, null, "", "");
         });
      break;
    case 6:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setTimeout(value);
      break;
    case 7:
      var value = new proto.neurun.HTTPAuth;
      reader.readMessage(value,proto.neurun.HTTPAuth.deserializeBinaryFromReader);
      msg.setAuth(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setFollowredirects(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setVerifyssl(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setExpectedstatuscode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.neurun.HTTPPayload.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.neurun.HTTPPayload.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.neurun.HTTPPayload} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neurun.HTTPPayload.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMethod();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getBody_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getHeadersMap(true);
  if (f && f.getLength() > 0) {
jspb.internal.public_for_gencode.serializeMapToBinary(
    message.getHeadersMap(true),
    4,
    writer,
    jspb.BinaryWriter.prototype.writeString,
    jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getQueryparamsMap(true);
  if (f && f.getLength() > 0) {
jspb.internal.public_for_gencode.serializeMapToBinary(
    message.getQueryparamsMap(true),
    5,
    writer,
    jspb.BinaryWriter.prototype.writeString,
    jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getTimeout();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getAuth();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.neurun.HTTPAuth.serializeBinaryToWriter
    );
  }
  f = message.getFollowredirects();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getVerifyssl();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
  f = message.getExpectedstatuscode();
  if (f !== 0) {
    writer.writeInt32(
      10,
      f
    );
  }
};


/**
 * optional string url = 1;
 * @return {string}
 */
proto.neurun.HTTPPayload.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.neurun.HTTPPayload} returns this
 */
proto.neurun.HTTPPayload.prototype.setUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string method = 2;
 * @return {string}
 */
proto.neurun.HTTPPayload.prototype.getMethod = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.neurun.HTTPPayload} returns this
 */
proto.neurun.HTTPPayload.prototype.setMethod = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bytes body = 3;
 * @return {string}
 */
proto.neurun.HTTPPayload.prototype.getBody = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes body = 3;
 * This is a type-conversion wrapper around `getBody()`
 * @return {string}
 */
proto.neurun.HTTPPayload.prototype.getBody_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBody()));
};


/**
 * optional bytes body = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBody()`
 * @return {!Uint8Array}
 */
proto.neurun.HTTPPayload.prototype.getBody_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBody()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.neurun.HTTPPayload} returns this
 */
proto.neurun.HTTPPayload.prototype.setBody = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * map<string, string> headers = 4;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.neurun.HTTPPayload.prototype.getHeadersMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 4, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.neurun.HTTPPayload} returns this
 */
proto.neurun.HTTPPayload.prototype.clearHeadersMap = function() {
  this.getHeadersMap().clear();
  return this;
};


/**
 * map<string, string> queryParams = 5;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.neurun.HTTPPayload.prototype.getQueryparamsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 5, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.neurun.HTTPPayload} returns this
 */
proto.neurun.HTTPPayload.prototype.clearQueryparamsMap = function() {
  this.getQueryparamsMap().clear();
  return this;
};


/**
 * optional google.protobuf.Duration timeout = 6;
 * @return {?proto.google.protobuf.Duration}
 */
proto.neurun.HTTPPayload.prototype.getTimeout = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 6));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.neurun.HTTPPayload} returns this
*/
proto.neurun.HTTPPayload.prototype.setTimeout = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.neurun.HTTPPayload} returns this
 */
proto.neurun.HTTPPayload.prototype.clearTimeout = function() {
  return this.setTimeout(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.neurun.HTTPPayload.prototype.hasTimeout = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional HTTPAuth auth = 7;
 * @return {?proto.neurun.HTTPAuth}
 */
proto.neurun.HTTPPayload.prototype.getAuth = function() {
  return /** @type{?proto.neurun.HTTPAuth} */ (
    jspb.Message.getWrapperField(this, proto.neurun.HTTPAuth, 7));
};


/**
 * @param {?proto.neurun.HTTPAuth|undefined} value
 * @return {!proto.neurun.HTTPPayload} returns this
*/
proto.neurun.HTTPPayload.prototype.setAuth = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.neurun.HTTPPayload} returns this
 */
proto.neurun.HTTPPayload.prototype.clearAuth = function() {
  return this.setAuth(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.neurun.HTTPPayload.prototype.hasAuth = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional bool followRedirects = 8;
 * @return {boolean}
 */
proto.neurun.HTTPPayload.prototype.getFollowredirects = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.neurun.HTTPPayload} returns this
 */
proto.neurun.HTTPPayload.prototype.setFollowredirects = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional bool verifySSL = 9;
 * @return {boolean}
 */
proto.neurun.HTTPPayload.prototype.getVerifyssl = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.neurun.HTTPPayload} returns this
 */
proto.neurun.HTTPPayload.prototype.setVerifyssl = function(value) {
  return jspb.Message.setProto3BooleanField(this, 9, value);
};


/**
 * optional int32 expectedStatusCode = 10;
 * @return {number}
 */
proto.neurun.HTTPPayload.prototype.getExpectedstatuscode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.neurun.HTTPPayload} returns this
 */
proto.neurun.HTTPPayload.prototype.setExpectedstatuscode = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.neurun.HTTPAuth.oneofGroups_ = [[1,2,3]];

/**
 * @enum {number}
 */
proto.neurun.HTTPAuth.AuthTypeCase = {
  AUTH_TYPE_NOT_SET: 0,
  BASIC: 1,
  BEARER: 2,
  APIKEY: 3
};

/**
 * @return {proto.neurun.HTTPAuth.AuthTypeCase}
 */
proto.neurun.HTTPAuth.prototype.getAuthTypeCase = function() {
  return /** @type {proto.neurun.HTTPAuth.AuthTypeCase} */(jspb.Message.computeOneofCase(this, proto.neurun.HTTPAuth.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.neurun.HTTPAuth.prototype.toObject = function(opt_includeInstance) {
  return proto.neurun.HTTPAuth.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.neurun.HTTPAuth} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neurun.HTTPAuth.toObject = function(includeInstance, msg) {
  var f, obj = {
basic: (f = msg.getBasic()) && proto.neurun.HTTPBasicAuth.toObject(includeInstance, f),
bearer: (f = msg.getBearer()) && proto.neurun.HTTPBearerAuth.toObject(includeInstance, f),
apikey: (f = msg.getApikey()) && proto.neurun.HTTPApiKeyAuth.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.neurun.HTTPAuth}
 */
proto.neurun.HTTPAuth.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.neurun.HTTPAuth;
  return proto.neurun.HTTPAuth.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.neurun.HTTPAuth} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.neurun.HTTPAuth}
 */
proto.neurun.HTTPAuth.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.neurun.HTTPBasicAuth;
      reader.readMessage(value,proto.neurun.HTTPBasicAuth.deserializeBinaryFromReader);
      msg.setBasic(value);
      break;
    case 2:
      var value = new proto.neurun.HTTPBearerAuth;
      reader.readMessage(value,proto.neurun.HTTPBearerAuth.deserializeBinaryFromReader);
      msg.setBearer(value);
      break;
    case 3:
      var value = new proto.neurun.HTTPApiKeyAuth;
      reader.readMessage(value,proto.neurun.HTTPApiKeyAuth.deserializeBinaryFromReader);
      msg.setApikey(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.neurun.HTTPAuth.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.neurun.HTTPAuth.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.neurun.HTTPAuth} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neurun.HTTPAuth.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBasic();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.neurun.HTTPBasicAuth.serializeBinaryToWriter
    );
  }
  f = message.getBearer();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.neurun.HTTPBearerAuth.serializeBinaryToWriter
    );
  }
  f = message.getApikey();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.neurun.HTTPApiKeyAuth.serializeBinaryToWriter
    );
  }
};


/**
 * optional HTTPBasicAuth basic = 1;
 * @return {?proto.neurun.HTTPBasicAuth}
 */
proto.neurun.HTTPAuth.prototype.getBasic = function() {
  return /** @type{?proto.neurun.HTTPBasicAuth} */ (
    jspb.Message.getWrapperField(this, proto.neurun.HTTPBasicAuth, 1));
};


/**
 * @param {?proto.neurun.HTTPBasicAuth|undefined} value
 * @return {!proto.neurun.HTTPAuth} returns this
*/
proto.neurun.HTTPAuth.prototype.setBasic = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.neurun.HTTPAuth.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.neurun.HTTPAuth} returns this
 */
proto.neurun.HTTPAuth.prototype.clearBasic = function() {
  return this.setBasic(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.neurun.HTTPAuth.prototype.hasBasic = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional HTTPBearerAuth bearer = 2;
 * @return {?proto.neurun.HTTPBearerAuth}
 */
proto.neurun.HTTPAuth.prototype.getBearer = function() {
  return /** @type{?proto.neurun.HTTPBearerAuth} */ (
    jspb.Message.getWrapperField(this, proto.neurun.HTTPBearerAuth, 2));
};


/**
 * @param {?proto.neurun.HTTPBearerAuth|undefined} value
 * @return {!proto.neurun.HTTPAuth} returns this
*/
proto.neurun.HTTPAuth.prototype.setBearer = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.neurun.HTTPAuth.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.neurun.HTTPAuth} returns this
 */
proto.neurun.HTTPAuth.prototype.clearBearer = function() {
  return this.setBearer(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.neurun.HTTPAuth.prototype.hasBearer = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional HTTPApiKeyAuth apiKey = 3;
 * @return {?proto.neurun.HTTPApiKeyAuth}
 */
proto.neurun.HTTPAuth.prototype.getApikey = function() {
  return /** @type{?proto.neurun.HTTPApiKeyAuth} */ (
    jspb.Message.getWrapperField(this, proto.neurun.HTTPApiKeyAuth, 3));
};


/**
 * @param {?proto.neurun.HTTPApiKeyAuth|undefined} value
 * @return {!proto.neurun.HTTPAuth} returns this
*/
proto.neurun.HTTPAuth.prototype.setApikey = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.neurun.HTTPAuth.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.neurun.HTTPAuth} returns this
 */
proto.neurun.HTTPAuth.prototype.clearApikey = function() {
  return this.setApikey(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.neurun.HTTPAuth.prototype.hasApikey = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.neurun.HTTPBasicAuth.prototype.toObject = function(opt_includeInstance) {
  return proto.neurun.HTTPBasicAuth.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.neurun.HTTPBasicAuth} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neurun.HTTPBasicAuth.toObject = function(includeInstance, msg) {
  var f, obj = {
username: jspb.Message.getFieldWithDefault(msg, 1, ""),
password: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.neurun.HTTPBasicAuth}
 */
proto.neurun.HTTPBasicAuth.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.neurun.HTTPBasicAuth;
  return proto.neurun.HTTPBasicAuth.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.neurun.HTTPBasicAuth} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.neurun.HTTPBasicAuth}
 */
proto.neurun.HTTPBasicAuth.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setUsername(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setPassword(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.neurun.HTTPBasicAuth.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.neurun.HTTPBasicAuth.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.neurun.HTTPBasicAuth} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neurun.HTTPBasicAuth.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUsername();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPassword();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string username = 1;
 * @return {string}
 */
proto.neurun.HTTPBasicAuth.prototype.getUsername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.neurun.HTTPBasicAuth} returns this
 */
proto.neurun.HTTPBasicAuth.prototype.setUsername = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string password = 2;
 * @return {string}
 */
proto.neurun.HTTPBasicAuth.prototype.getPassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.neurun.HTTPBasicAuth} returns this
 */
proto.neurun.HTTPBasicAuth.prototype.setPassword = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.neurun.HTTPBearerAuth.prototype.toObject = function(opt_includeInstance) {
  return proto.neurun.HTTPBearerAuth.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.neurun.HTTPBearerAuth} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neurun.HTTPBearerAuth.toObject = function(includeInstance, msg) {
  var f, obj = {
token: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.neurun.HTTPBearerAuth}
 */
proto.neurun.HTTPBearerAuth.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.neurun.HTTPBearerAuth;
  return proto.neurun.HTTPBearerAuth.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.neurun.HTTPBearerAuth} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.neurun.HTTPBearerAuth}
 */
proto.neurun.HTTPBearerAuth.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setToken(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.neurun.HTTPBearerAuth.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.neurun.HTTPBearerAuth.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.neurun.HTTPBearerAuth} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neurun.HTTPBearerAuth.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getToken();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string token = 1;
 * @return {string}
 */
proto.neurun.HTTPBearerAuth.prototype.getToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.neurun.HTTPBearerAuth} returns this
 */
proto.neurun.HTTPBearerAuth.prototype.setToken = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.neurun.HTTPApiKeyAuth.prototype.toObject = function(opt_includeInstance) {
  return proto.neurun.HTTPApiKeyAuth.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.neurun.HTTPApiKeyAuth} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neurun.HTTPApiKeyAuth.toObject = function(includeInstance, msg) {
  var f, obj = {
key: jspb.Message.getFieldWithDefault(msg, 1, ""),
value: jspb.Message.getFieldWithDefault(msg, 2, ""),
location: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.neurun.HTTPApiKeyAuth}
 */
proto.neurun.HTTPApiKeyAuth.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.neurun.HTTPApiKeyAuth;
  return proto.neurun.HTTPApiKeyAuth.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.neurun.HTTPApiKeyAuth} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.neurun.HTTPApiKeyAuth}
 */
proto.neurun.HTTPApiKeyAuth.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setKey(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setValue(value);
      break;
    case 3:
      var value = /** @type {!proto.neurun.HTTPApiKeyLocation} */ (reader.readEnum());
      msg.setLocation(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.neurun.HTTPApiKeyAuth.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.neurun.HTTPApiKeyAuth.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.neurun.HTTPApiKeyAuth} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.neurun.HTTPApiKeyAuth.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getValue();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLocation();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * optional string key = 1;
 * @return {string}
 */
proto.neurun.HTTPApiKeyAuth.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.neurun.HTTPApiKeyAuth} returns this
 */
proto.neurun.HTTPApiKeyAuth.prototype.setKey = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string value = 2;
 * @return {string}
 */
proto.neurun.HTTPApiKeyAuth.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.neurun.HTTPApiKeyAuth} returns this
 */
proto.neurun.HTTPApiKeyAuth.prototype.setValue = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional HTTPApiKeyLocation location = 3;
 * @return {!proto.neurun.HTTPApiKeyLocation}
 */
proto.neurun.HTTPApiKeyAuth.prototype.getLocation = function() {
  return /** @type {!proto.neurun.HTTPApiKeyLocation} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.neurun.HTTPApiKeyLocation} value
 * @return {!proto.neurun.HTTPApiKeyAuth} returns this
 */
proto.neurun.HTTPApiKeyAuth.prototype.setLocation = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * @enum {number}
 */
proto.neurun.TaskType = {
  TASK_TYPE_UNSPECIFIED: 0,
  TASK_TYPE_LOG: 1,
  TASK_TYPE_HTTP: 2
};

/**
 * @enum {number}
 */
proto.neurun.TaskStatus = {
  TASK_STATUS_UNSPECIFIED: 0,
  TASK_STATUS_PENDING: 1,
  TASK_STATUS_RUNNING: 2,
  TASK_STATUS_COMPLETED: 3,
  TASK_STATUS_FAILED: 4
};

/**
 * @enum {number}
 */
proto.neurun.HTTPApiKeyLocation = {
  HTTP_API_KEY_LOCATION_UNSPECIFIED: 0,
  HTTP_API_KEY_LOCATION_HEADER: 1,
  HTTP_API_KEY_LOCATION_QUERY: 2
};

goog.object.extend(exports, proto.neurun);
