/**
 * @fileoverview gRPC-Web generated client stub for neurun
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.33.1
// source: workflow.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as workflow_pb from './workflow_pb'; // proto import: "workflow.proto"


export class WorkflowServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateWorkflow = new grpcWeb.MethodDescriptor(
    '/neurun.WorkflowService/CreateWorkflow',
    grpcWeb.MethodType.UNARY,
    workflow_pb.CreateWorkflowRequest,
    workflow_pb.WorkflowResponse,
    (request: workflow_pb.CreateWorkflowRequest) => {
      return request.serializeBinary();
    },
    workflow_pb.WorkflowResponse.deserializeBinary
  );

  createWorkflow(
    request: workflow_pb.CreateWorkflowRequest,
    metadata?: grpcWeb.Metadata | null): Promise<workflow_pb.WorkflowResponse>;

  createWorkflow(
    request: workflow_pb.CreateWorkflowRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: workflow_pb.WorkflowResponse) => void): grpcWeb.ClientReadableStream<workflow_pb.WorkflowResponse>;

  createWorkflow(
    request: workflow_pb.CreateWorkflowRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: workflow_pb.WorkflowResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/neurun.WorkflowService/CreateWorkflow',
        request,
        metadata || {},
        this.methodDescriptorCreateWorkflow,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/neurun.WorkflowService/CreateWorkflow',
    request,
    metadata || {},
    this.methodDescriptorCreateWorkflow);
  }

  methodDescriptorGetWorkflow = new grpcWeb.MethodDescriptor(
    '/neurun.WorkflowService/GetWorkflow',
    grpcWeb.MethodType.UNARY,
    workflow_pb.GetWorkflowRequest,
    workflow_pb.WorkflowResponse,
    (request: workflow_pb.GetWorkflowRequest) => {
      return request.serializeBinary();
    },
    workflow_pb.WorkflowResponse.deserializeBinary
  );

  getWorkflow(
    request: workflow_pb.GetWorkflowRequest,
    metadata?: grpcWeb.Metadata | null): Promise<workflow_pb.WorkflowResponse>;

  getWorkflow(
    request: workflow_pb.GetWorkflowRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: workflow_pb.WorkflowResponse) => void): grpcWeb.ClientReadableStream<workflow_pb.WorkflowResponse>;

  getWorkflow(
    request: workflow_pb.GetWorkflowRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: workflow_pb.WorkflowResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/neurun.WorkflowService/GetWorkflow',
        request,
        metadata || {},
        this.methodDescriptorGetWorkflow,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/neurun.WorkflowService/GetWorkflow',
    request,
    metadata || {},
    this.methodDescriptorGetWorkflow);
  }

  methodDescriptorExecuteWorkflow = new grpcWeb.MethodDescriptor(
    '/neurun.WorkflowService/ExecuteWorkflow',
    grpcWeb.MethodType.SERVER_STREAMING,
    workflow_pb.ExecuteWorkflowRequest,
    workflow_pb.ExecuteWorkflowResponse,
    (request: workflow_pb.ExecuteWorkflowRequest) => {
      return request.serializeBinary();
    },
    workflow_pb.ExecuteWorkflowResponse.deserializeBinary
  );

  executeWorkflow(
    request: workflow_pb.ExecuteWorkflowRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<workflow_pb.ExecuteWorkflowResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/neurun.WorkflowService/ExecuteWorkflow',
      request,
      metadata || {},
      this.methodDescriptorExecuteWorkflow);
  }

}

